server {
    listen 8444 ssl;
    server_name localhost;
    root /var/www/example.com;

    # Here use your certificate
    ssl_certificate     /opt/certs/server.crt;
    ssl_certificate_key /opt/certs/server.key;
    
    ssl_protocols       TLSv1.3;
    ssl_conf_command    Groups X25519MLKEM768;
    ssl_session_cache   off;
    ssl_session_tickets off;

    location = /api/direct {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }
    location /api/payload/1kb    { try_files /1kb.bin =404; }
    location /api/payload/100kb  { try_files /100kb.bin =404; }
    location /api/payload/1mb    { try_files /1mb.bin =404; }
}

